import { FootballMatch } from '../types/football';

export interface LiveOddSelection {
  id: string;
  name: string;
  subTitle?: string;
  odds: number; // Current live bookmaker decimal odds (e.g. 2.35)
  fairOdds: number; // Pure mathematical fair odds by AI (e.g. 2.05)
  previousOdds: number;
  trend: 'UP' | 'DOWN' | 'STABLE';
  delta: number;
  probability: number; // in percent (e.g. 48.8%)
  evPercentage: number; // e.g. +14.6% or -3.2%
  isValue: boolean; // EV > +3%
  marketId: string;
}

export interface LiveBettingMarket {
  id: string;
  title: string;
  description: string;
  category: '1X2' | 'NEXT_GOAL' | 'OVER_UNDER' | 'BTTS' | 'DOUBLE_CHANCE';
  selections: LiveOddSelection[];
  isSuspended: boolean;
}

export interface DynamicOddsState {
  markets: LiveBettingMarket[];
  topValueBet: LiveOddSelection | null;
  momentumMultiplierHome: number;
  momentumMultiplierAway: number;
  expectedGoalsRemainingHome: number;
  expectedGoalsRemainingAway: number;
  timeDecayFactor: number;
}

// Factorial helper for Poisson
function factorial(n: number): number {
  if (n <= 1) return 1;
  let res = 1;
  for (let i = 2; i <= n; i++) res *= i;
  return res;
}

// Poisson probability P(X = k) = (lambda^k * e^-lambda) / k!
function poissonProb(lambda: number, k: number): number {
  if (lambda <= 0) return k === 0 ? 1 : 0;
  return (Math.pow(lambda, k) * Math.exp(-lambda)) / factorial(k);
}

/**
 * Calculates live betting odds in real time dynamically driven by:
 * 1. Current Match minute (time decay)
 * 2. Current Score
 * 3. Momentum index (% dominance)
 * 4. Cumulative xG generated by the live simulation
 * 5. Recent events (dangerous attacks, shots on target)
 */
export function calculateDynamicLiveOdds(
  match: FootballMatch,
  previousOddsMap?: Record<string, number>
): DynamicOddsState {
  const { minute, score, stats, momentum } = match;
  const currentTotalGoals = score.home + score.away;

  // 1. Time remaining ratio (from 1.0 at min 0 down to 0.05 at min 90)
  const minutesRemaining = Math.max(1, 90 - minute);
  const timeFraction = minutesRemaining / 90;
  const timeDecayFactor = Number(timeFraction.toFixed(3));

  // 2. Momentum impact: scale from 0.7 (oppressed) to 1.5 (surging pressure)
  // 50% dominance = 1.0 multiplier
  const homeMomRatio = momentum.homeDominance / 50;
  const awayMomRatio = momentum.awayDominance / 50;

  const momentumMultiplierHome = Number(Math.max(0.65, Math.min(1.6, 0.5 + 0.5 * homeMomRatio)).toFixed(2));
  const momentumMultiplierAway = Number(Math.max(0.65, Math.min(1.6, 0.5 + 0.5 * awayMomRatio)).toFixed(2));

  // 3. xG pace impact: calculate xG generation velocity per 15 mins
  // Baseline average expected goals per 90 min is ~1.45 for home, ~1.25 for away
  const homeXgVelocity = minute > 0 ? (stats.xg.home / minute) * 90 : 1.45;
  const awayXgVelocity = minute > 0 ? (stats.xg.away / minute) * 90 : 1.25;

  // Expected goals for the remaining time
  const lambdaHome = Math.max(
    0.05,
    ((homeXgVelocity * 0.5 + 1.45 * 0.5) * (minutesRemaining / 90)) *
      momentumMultiplierHome
  );
  const lambdaAway = Math.max(
    0.05,
    ((awayXgVelocity * 0.5 + 1.25 * 0.5) * (minutesRemaining / 90)) *
      momentumMultiplierAway
  );

  // 4. Calculate bivariate matrix of remaining score outcomes (0 to 5 goals each)
  let probHomeWin = 0;
  let probDraw = 0;
  let probAwayWin = 0;

  // Over/Under probabilities
  let probOver15 = 0;
  let probOver25 = 0;
  let probOver35 = 0;

  // BTTS probability
  let probBtts = 0;

  for (let gh = 0; gh <= 5; gh++) {
    const pH = poissonProb(lambdaHome, gh);
    for (let ga = 0; ga <= 5; ga++) {
      const pA = poissonProb(lambdaAway, ga);
      const jointP = pH * pA;

      const finalHome = score.home + gh;
      const finalAway = score.away + ga;
      const finalTotal = finalHome + finalAway;

      if (finalHome > finalAway) probHomeWin += jointP;
      else if (finalHome === finalAway) probDraw += jointP;
      else probAwayWin += jointP;

      if (finalTotal > 1.5) probOver15 += jointP;
      if (finalTotal > 2.5) probOver25 += jointP;
      if (finalTotal > 3.5) probOver35 += jointP;

      if (finalHome > 0 && finalAway > 0) probBtts += jointP;
    }
  }

  // Normalize 1X2 probabilities
  const sum1X2 = probHomeWin + probDraw + probAwayWin || 1;
  probHomeWin /= sum1X2;
  probDraw /= sum1X2;
  probAwayWin /= sum1X2;

  // Next Goal calculation
  const probNoMoreGoals = Math.exp(-(lambdaHome + lambdaAway));
  const probAnyGoal = 1 - probNoMoreGoals;
  const nextGoalHomeShare = lambdaHome / (lambdaHome + lambdaAway || 1);
  const probNextGoalHome = probAnyGoal * nextGoalHomeShare;
  const probNextGoalAway = probAnyGoal * (1 - nextGoalHomeShare);

  // Helper to construct odd selection with trend and margin
  const buildOdd = (
    id: string,
    name: string,
    fairProb: number,
    marketId: string,
    subTitle?: string
  ): LiveOddSelection => {
    const clampedProb = Math.max(0.02, Math.min(0.97, fairProb));
    const pureFairOdd = 1 / clampedProb;

    // Bookmaker margin (~5.5%) + market lag
    // Bookmakers slightly lag when momentum spikes, creating +EV for user
    const bookmakerMargin = 1.055;
    // Introduce dynamic lag/advantage based on rapid momentum swing
    const momAdvantage = marketId === '1X2' && id.includes('home')
      ? (momentum.homeDominance - 50) * 0.003
      : marketId === '1X2' && id.includes('away')
      ? (momentum.awayDominance - 50) * 0.003
      : 0;

    const rawBookieOdds = (1 / (clampedProb * bookmakerMargin)) * (1 + momAdvantage);
    const bookmakerOdds = Number(Math.max(1.02, Math.min(45.0, rawBookieOdds)).toFixed(2));
    const fairOdds = Number(Math.max(1.02, Math.min(45.0, pureFairOdd)).toFixed(2));

    // Expected Value %: (fairProb * bookmakerOdds - 1) * 100
    const evPercentage = Number(((clampedProb * bookmakerOdds - 1) * 100).toFixed(1));
    const isValue = evPercentage >= 3.0;

    // Previous odds comparison
    const prev = previousOddsMap?.[id] || bookmakerOdds;
    let trend: 'UP' | 'DOWN' | 'STABLE' = 'STABLE';
    const delta = Number((bookmakerOdds - prev).toFixed(2));
    if (delta > 0.02) trend = 'UP';
    else if (delta < -0.02) trend = 'DOWN';

    return {
      id,
      name,
      subTitle,
      odds: bookmakerOdds,
      fairOdds,
      previousOdds: prev,
      trend,
      delta,
      probability: Number((clampedProb * 100).toFixed(1)),
      evPercentage,
      isValue,
      marketId,
    };
  };

  // 5. Construct Markets
  // Market 1: 1X2 Match Winner
  const market1X2: LiveBettingMarket = {
    id: '1X2',
    title: 'Résultat du Match (1X2)',
    description: 'Pari en direct sur le vainqueur final du match à la 90e minute',
    category: '1X2',
    isSuspended: false,
    selections: [
      buildOdd('1x2-home', `Victoire ${match.homeTeam.shortName}`, probHomeWin, '1X2', '1 - Domicile'),
      buildOdd('1x2-draw', 'Match Nul', probDraw, '1X2', 'X - Nul'),
      buildOdd('1x2-away', `Victoire ${match.awayTeam.shortName}`, probAwayWin, '1X2', '2 - Extérieur'),
    ],
  };

  // Market 2: Prochain But (Next Goal)
  const marketNextGoal: LiveBettingMarket = {
    id: 'NEXT_GOAL',
    title: 'Prochain But Inscrit',
    description: 'Quelle équipe marquera le prochain but ou fin de match sans autre but ?',
    category: 'NEXT_GOAL',
    isSuspended: false,
    selections: [
      buildOdd('next-home', `${match.homeTeam.shortName} marque le prochain`, probNextGoalHome, 'NEXT_GOAL', `But #${currentTotalGoals + 1}`),
      buildOdd('next-none', 'Aucun autre but marqué', probNoMoreGoals, 'NEXT_GOAL', 'Score inchangé'),
      buildOdd('next-away', `${match.awayTeam.shortName} marque le prochain`, probNextGoalAway, 'NEXT_GOAL', `But #${currentTotalGoals + 1}`),
    ],
  };

  // Market 3: Plus / Moins de Buts (Over / Under)
  // Dynamically choose relevant threshold based on current score
  const dynamicThreshold = currentTotalGoals >= 3 ? 3.5 : currentTotalGoals >= 2 ? 2.5 : 2.5;
  const overProb = dynamicThreshold === 3.5 ? probOver35 : probOver25;
  const underProb = 1 - overProb;

  const marketOverUnder: LiveBettingMarket = {
    id: 'OVER_UNDER',
    title: `Total Buts (Plus / Moins ${dynamicThreshold})`,
    description: `Nombre cumulé de buts inscrits dans le match (Actuel: ${currentTotalGoals} buts)`,
    category: 'OVER_UNDER',
    isSuspended: false,
    selections: [
      buildOdd('ou-over', `Plus de ${dynamicThreshold} Buts`, overProb, 'OVER_UNDER', `+ de ${dynamicThreshold}`),
      buildOdd('ou-under', `Moins de ${dynamicThreshold} Buts`, underProb, 'OVER_UNDER', `- de ${dynamicThreshold}`),
    ],
  };

  // Market 4: Les 2 Équipes Marquent (BTTS)
  // If both teams already scored, prob is 1.0 (settled)
  const alreadyBtts = score.home > 0 && score.away > 0;
  const bttsYesProb = alreadyBtts ? 0.99 : probBtts;
  const bttsNoProb = 1 - bttsYesProb;

  const marketBtts: LiveBettingMarket = {
    id: 'BTTS',
    title: 'Les Deux Équipes Marquent',
    description: 'Est-ce que les deux équipes trouveront le chemin des filets ?',
    category: 'BTTS',
    isSuspended: alreadyBtts,
    selections: [
      buildOdd('btts-yes', alreadyBtts ? 'Gagné (Déjà marqué)' : 'Oui (Les 2 marquent)', bttsYesProb, 'BTTS'),
      buildOdd('btts-no', alreadyBtts ? 'Perdu' : 'Non', bttsNoProb, 'BTTS'),
    ],
  };

  // Market 5: Double Chance
  const prob1X = probHomeWin + probDraw;
  const prob12 = probHomeWin + probAwayWin;
  const probX2 = probDraw + probAwayWin;

  const marketDoubleChance: LiveBettingMarket = {
    id: 'DOUBLE_CHANCE',
    title: 'Double Chance Direct',
    description: 'Couvrez deux issues possibles sur le score final',
    category: 'DOUBLE_CHANCE',
    isSuspended: false,
    selections: [
      buildOdd('dc-1x', `1X (${match.homeTeam.shortName} ou Nul)`, prob1X, 'DOUBLE_CHANCE'),
      buildOdd('dc-12', `12 (${match.homeTeam.shortName} ou ${match.awayTeam.shortName})`, prob12, 'DOUBLE_CHANCE'),
      buildOdd('dc-x2', `X2 (Nul ou ${match.awayTeam.shortName})`, probX2, 'DOUBLE_CHANCE'),
    ],
  };

  const markets = [market1X2, marketNextGoal, marketOverUnder, marketBtts, marketDoubleChance];

  // Find top value bet with highest positive EV%
  let topValueBet: LiveOddSelection | null = null;
  let highestEv = 3.0; // threshold

  markets.forEach((m) => {
    m.selections.forEach((sel) => {
      if (sel.evPercentage > highestEv) {
        highestEv = sel.evPercentage;
        topValueBet = sel;
      }
    });
  });

  return {
    markets,
    topValueBet,
    momentumMultiplierHome,
    momentumMultiplierAway,
    expectedGoalsRemainingHome: Number(lambdaHome.toFixed(2)),
    expectedGoalsRemainingAway: Number(lambdaAway.toFixed(2)),
    timeDecayFactor,
  };
}
